
[Network]
  Address = ":19135"

[Players]
  Folder = "players"
  MaxCount = 0
  MaximumChunkRadius = 32
  SaveData = true

[Resources]
  AutoBuildPack = true
  Folder = "resources"
  Required = true

[Server]
  AuthEnabled = true
  DisableJoinQuitMessages = false
  Name = "Dragonfly Server"

[World]
  Folder = "world"
  SaveData = true
